### PR TITLE
Login enhancements

### PR DESCRIPTION
**Pull request by wkloucek**

### CODE REVIEW

**Comment by wkloucek** [comment]
@ChrisEdS I would like to merge this to master. Is this ok for you? I tested it and works fine for me :+1:

**Comment by ChrisEdS** [comment]
@hurradieweltgehtunter has another idea regarding how to implement the QR-Codes. Can we wait some more hours before we merge?

**Comment by hurradieweltgehtunter** [comment]
Chris contacted me about some css help for this and while working on it some ideas came to my mind about this which I want to share with you.
Basically it works like it is right now, nothing wrong with it. But regarding usability and user experience we could improve it a little bit. Let's see:

### Target group
Most QNAP users are home users meaning people who have their NAS at home, maybe some bigger QNAPs in companies but my guess is that most of the users do not have deeper IT skills. This means that the easier the setup process is the more positive the impression is (of QNAP but also of ownCloud). Meaning also the less distracting elements or options the better the perception (Apple principle).
Let's see what this means for the current implementation.

QR codes are an easy way to link to targets - so good thinking implementing them. But I encourage you to think it further:

### Problem 1: QR codes are very small/hover scaling effect
I tested the QR codes and my camera had problems recognizing them because they are very small which leads to a first frustration. The scaling hover effect is kind of a solution but hover effects have the problem that the user needs to think about it first to hover the qr codes - which is kinda contradictory (QR codes are for mobile, why should I hover with my mouse?)

### Problem 2: Opening the login page on mobile
If the user opens the login page on mobile the qr codes are still shown. In this case they are useless and in my own experience I find it annoying if I experience this behaviour in a software. Since they are not clickable it leads to frustration.
Also since both QR codes are shown it is at least one element which is useless - either the iOS QR code when the user is on Android or the Android QR code when he's on iOS.

## OK but what's the solution?
### Solution 1
Let's add a mobile detection script (there are JS scripts which do that). 
- If the user is on mobile:
-- If the user is on Android: Show "Get it on Google play store" Button
-- else if the user is on iOS: Show "Get is on App Store" Button
- else if not on mobile: show QR codes

Use the official buttons for this, people are used to them: https://play.google.com/intl/en_us/badges/ and https://developer.apple.com/app-store/marketing/guidelines/

### Solution 2 (even more sophisticated)
Based on solution 1. Let's assume the user is not on mobile:
Show only 1 QR code. Scanning this leads the user to (for example) qnap.owncloud.com. This URL runs a JS or even PHP script whichs detects which device is used and forwards the user to the corresponding app store.
Benefits: Only 1 QR code is shown which is less distracting, requires the user to even think less and we additionally could track how often the qr codes are scanned (if we are interested in this).
As only 1 QR code is shown there is more space below the login form so the qr code could be shown bigger (see Problem 1) and it could be more future proof in terms of spacing ( I think of the upcoming login button (10.7.1) below the login form).

## Meh ok, you might be right but I don't wanna put so much work in it ....
Agreed. While this sounds maybe time consuming it isn't. I'm happy to help out here, I think it could be done in half a day max.
For solution 2 we need our admins to set up the subdomain which should also not take too long.

In my opinion we should take these steps to round up the user experience here. I know, those are small details and maybe edge cases but IMHO this separates a "at least it's working" solution from a "nice user experience" solution.

Let me know what you think of this and if you need my help.

**Comment by hurradieweltgehtunter** [comment]
mobile detection is now included. 
For the QR code changes please advise.

Another idea: Include a link to download the desktop client when on desktop

**Comment by wkloucek** [comment]
@hurradieweltgehtunter Thanks for your implementation and input! I need to talk with Jörg about this and will come back to you :-)

**Comment by wkloucek** [comment]
@ChrisEdS @hurradieweltgehtunter We will first go with the current implementation and can go for a more sophisticated solution later

**Pull request merged**
